name: project_chatapp_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Untuk mengizinkan akses internet, tambahkan permission di android/app/src/main/AndroidManifest.xml:
  # <uses-permission android:name="android.permission.INTERNET"/>
