name: Kokit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  record: ^5.1.2
  just_audio: ^0.9.41
  audioplayers: ^6.1.0
  web_socket_channel: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Kokit.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To allow internet access, add permission in android/app/src/main/AndroidManifest.xml:
  # <uses-permission android:name="android.permission.INTERNET"/>
